<dr>
<center>
## Visual Analytics for Policy and Management: Exercise 1

### Univariate Case 

### by Maria Zepeda Flores
</center>

Data to be used:
```{r}
link='https://github.com/EvansDataScience/VisualAnalytics_2_tabularData/raw/master/data/eduwa.rda'
load(file=url(link))
```


```{r, echo=FALSE, results = 'hide'}
#number of rows and columns
dim(eduwa) #nrow(eduwa) ncol(eduwa)
```

```{r, echo=FALSE, results = 'hide'}
names(eduwa)
```

```{r, echo=FALSE, results = 'hide'}
str(eduwa,width = 70,strict.width='cut')
```


```{r, echo=FALSE, results = 'hide'}
table(eduwa$LocaleType,exclude = 'nothing')
```

```{r, echo=FALSE, results = 'hide'}
absoluteT=table(eduwa$LocaleType,exclude = 'nothing')
prop.table(absoluteT)
ToPlot=prop.table(absoluteT)
```

```{r, echo=FALSE, results = 'hide'}
names(ToPlot)[5]='Unknown'
```

```{r, echo=FALSE, results = 'hide'}
library(ggplot2)
```

```{r, echo=FALSE, results = 'hide'}
tableFreq=as.data.frame(ToPlot)
names(tableFreq)=c("locale","pct")
```

```{r, echo=FALSE, results = 'hide'}
tableFreq
```

```{r, echo=FALSE,results = 'hide'}
tableFreqO=tableFreq[order(tableFreq$pct),]
tableFreqO
```

Plot 1:
```{r, results = 'hide'}
base = ggplot(data = tableFreqO, 
             aes(x = locale,
                 y = pct)) 


plot1 = base + geom_bar(fill ="gray",
                        stat = 'identity') + scale_x_discrete(limits=tableFreqO$locale) 
# y is just what it is!
plot1 
```

